### ISSUE TITLE
Add a set of closure exercises before iterators exercise.

### ISSUE THREAD

**Issue by divyaranjan1905** [rust-lang/rustlings#2096] opened 2024-09-01 13:47 UTC
I believe another set of exercises should be there before the 19th set on interators.  This would keep it consistent with [The Book](https://doc.rust-lang.org/book/ch13-01-closures.html) and also provide a better treatment for closures which aren't exactly intuitive to beginning Rustaceans. Closures are also good practice for functional programming. 

If this could be done, I'd be glad in creating a set of exercises to this end as a PR.

**Comment by mo8it** [comment] 2024-09-02 12:29
Very good idea, but duplicate of https://github.com/rust-lang/rustlings/issues/1746. Let's discuss it there :)

**Closed by mo8it** 2024-09-02 12:29 UTC
