### ISSUE TITLE
Add a optional arg to specify the start exercise in watch mode

### ISSUE THREAD

**Issue by Jaxx4Fun** [rust-lang/rustlings#1941] opened 2024-04-02 10:58 UTC
Sometimes I need to restart or update my IDE which means the rustlings running in the integrated terminal will be terminated and needs to be launched again. So I am wondering if it is necessary to add a optional arg, for example:
 `--start-from <exercise>`, **to skip the previous exercises** 
IMHO I know they are intact, because I have only restared rustlings without updating the code or anything else.

**Comment by mo8it** [comment] 2024-04-02 12:20
A very good suggestion, but a duplicate of https://github.com/rust-lang/rustlings/issues/729 which is planned for version 6 :)

**Closed by mo8it** 2024-04-02 12:20 UTC
