### ISSUE TITLE
Canonical Solutions

### ISSUE THREAD

**Issue by dustinroepsch** [rust-lang/rustlings#820] opened 2021-08-11 18:27 UTC
Hello!

It would be great if after you complete a file, it showed you a "good" solution. Sometimes it's hard to tell if I cheated on accident, or didn't learn the lesson I was supposed to. 

The hints feature is great and kinda serves this purpose, but I'd still appreciate solutions to the problems after I do them myself :)

**Comment by kaiuri** [comment] 2021-12-07 16:52
> Hello!
> 
> It would be great if after you complete a file, it showed you a "good" solution. Sometimes it's hard to tell if I cheated on accident, or didn't learn the lesson I was supposed to.
> 
> The hints feature is great and kinda serves this purpose, but I'd still appreciate solutions to the problems after I do them myself :)

I'd like that also, not quite automated though, a simple folder containing elegant solutions to the "tough" ones

**Comment by kaiuri** [comment] 2022-01-29 00:21
@itayperry I guess taking advantage of `rustc`'s awesome features like monomorphization, `std`, `core`, generics, traits, etc, is the way to go.

**Comment by itayperry** [comment] 2022-01-30 06:45
@kaiuri I just started learning :) so it would take a while. 
In short, regarding the issue at hand, I'm absolutely up for adding canonical solutions for all the exercises.

**Comment by kaiuri** [comment] 2022-02-06 21:45
> @kaiuri I just started learning :) so it would take a while. In short, regarding the issue at hand, I'm absolutely up for adding canonical solutions for all the exercises.

Hmmm... I think Rust is too expressive for canonical, maybe the most idiomatic solution would result in something approaching uniqueness.

**Comment by rytheo** [comment] 2022-02-07 04:31
Possible duplicate of #293

**Comment by pbaettig** [comment] 2022-03-28 20:14
That would be such a great feature! Rustlings is a awesome for learning the language but it would be great to compare ones own solution with an idiomatic "optimal" solution

**Comment by mo8it** [comment] 2024-03-27 20:37
Duplicate of https://github.com/rust-lang/rustlings/issues/293

**Closed by mo8it** 2024-03-27 20:37 UTC
