### ISSUE TITLE
Display hints/information after being done

### ISSUE THREAD

**Issue by moessler-bit** [rust-lang/rustlings#1643] opened 2023-08-28 08:53 UTC
- I think it would be very helpful to get some more information about the code when someone has completed it. Maybe even a reference to the rust docs. Sometimes there are links in the hints sometimes there are not. I think the hint is not only to help someone complete the exercise but rather a useful piece of inormation too if someone just managed to pass the exercise by try and fail until they did it. Therefore I think it should be displayed at all times when the code compiles sucessfully. 
- Or instead you could display resources in form of links from the rust docs at the start of each exercise. What I mean is to introduce something like hint but more in form of the whole documentation (links to rust book) about the used Datatypes, functions and more.
- I don't know if this is possible but maybe it would be great to sort the exercises like each chapter in the rust book. As an example vectors which are covered in chapter 8 but they are right after primitive types (chapter 3,4) in the rustlings course.

- I think there should be a way for rustlings watch to start at a specific file because at home i forgot to push my progress and have to do it again (it's probably good for me to repeat these exercises but it would be convenient). I think you could delete the files that you did already as a workaround

Please feel free to expand this issue with your ideas about this

**Comment by moessler-bit** [comment] 2023-08-28 08:57
What about one code example at the end of how it could have been solved? Reading code could also improve learning imo. And it might help someone to figure out that something could have been solved in a simpler way if they are too far off.

**Comment by theplasticbrick** [comment] 2023-10-13 22:43
This might be a bit more work than the rest of the suggestions, but what about having different difficulties that you can select for rustlings?
For instance:  
1. A "Beginner" course that has a slower buildup with more time spent on working through basic programming principles and is structured to be done alongside the Rust book.
2. A "Starting with Rust" course that doesn't spend as much time on how basic programming principles but rather how general principles are done in Rust.
3. An "Advanced Rust" course that skips past the intro stuff and allows you to keep your skills sharp using more difficult exercises(preferably repeatable ones that have multiple good ways to complete to allow for exploration of the language)

**Comment by mo8it** [comment] 2024-03-30 15:47
> I think it would be very helpful to get some more information about the code when someone has completed it. Maybe even a reference to the rust docs. Sometimes there are links in the hints sometimes there are not. I think the hint is not only to help someone complete the exercise but rather a useful piece of inormation too if someone just managed to pass the exercise by try and fail until they did it. Therefore I think it should be displayed at all times when the code compiles sucessfully.

> Or instead you could display resources in form of links from the rust docs at the start of each exercise. What I mean is to introduce something like hint but more in form of the whole documentation (links to rust book) about the used Datatypes, functions and more.

> What about one code example at the end of how it could have been solved? Reading code could also improve learning imo. And it might help someone to figure out that something could have been solved in a simpler way if they are too far off.

A very good idea, but I am closing since this can be achieved in the reference solutions https://github.com/rust-lang/rustlings/issues/293

> I think there should be a way for rustlings watch to start at a specific file because at home i forgot to push my progress and have to do it again (it's probably good for me to repeat these exercises but it would be convenient). I think you could delete the files that you did already as a workaround

This is a duplicate of https://github.com/rust-lang/rustlings/issues/729 and https://github.com/rust-lang/rustlings/issues/1920 which are planned for the next major version 6.0 :D

**Closed by mo8it** 2024-03-30 15:47 UTC

**Comment by mo8it** [comment] 2024-03-30 15:49
@theplasticbrick Could you please open a new issue with your suggestion? It would help us a lot to have issues organized and not mix things up :D
