### ISSUE TITLE
Don't recompile finished exercises on `rustlings watch`

### ISSUE THREAD

**Issue by feefladder** [rust-lang/rustlings#1843] opened 2024-01-30 15:30 UTC
When running `rustlings watch`, it compiles all completed exercises to see if they're finished. I didn't finish them all in one sitting, or may want to exit `rustlings watch` to do something else in my terminal (ofc I could open a second tab, but I don't want that).

What would be nice if rustlings somehow remembers what exercises have finished before, and whether the files have changed.

**Comment by mo8it** [comment] 2024-03-30 15:25
Duplicate of https://github.com/rust-lang/rustlings/issues/729

But this feature is now planned :)

**Closed by mo8it** 2024-03-30 15:25 UTC
Labels: C-enhancement, A-source
