### ISSUE TITLE
Structs1.rs makes use of String vs &str before `strings` exercises

### ISSUE THREAD

**Issue by prestontw** [rust-lang/rustlings#965] opened 2022-04-15 19:13 UTC
`structs1.rs` has the following snippet:
```rust
    #[test]
    fn classic_c_structs() {
        // TODO: Instantiate a classic c struct!
        // let green = 

        assert_eq!(green.name, "green");
        assert_eq!(green.hex, "#00FF00");
    }
```
The two kind of choices I would recommend to beginners to represent strings to avoid lifetime issues and lifetime verbosity are:
- `String`s and
- `&'static str` (which is only half avoiding the above lifetime issues---it still suffers from verbosity)

However, the difference between `&str` and `String` isn't covered yet in the flow we are in (`4.6.0`). Would it make sense from a pedagogic dependency standpoint to switch the order? Or to change the tests to nudge people towards using maybe an RGB representation instead of a string-based version? The rust compiler points us towards using `.to_string()`, but that might seem like opaque incantations: "why is this not a string?"

**Comment by diannasoreil** [comment] 2022-07-05 08:44
Gonna close this as a duplicate of #716.

**Closed by diannasoreil** 2022-07-05 08:44 UTC

**Comment by prestontw** [comment] 2022-07-31 20:24
Great, thank you!
