### ISSUE TITLE
cow1.rs last test is missing to_mut

### ISSUE THREAD

**Issue by quidnu** [rust-lang/rustlings#1611] opened 2023-08-05 18:13 UTC
cow1.rs last test `owned_mutation` is missing `to_mut` as described in the comment. As is it is identical to the previous test, `owned_no_mutation`

**Comment by wh5a** [comment] 2023-09-07 08:47
@quidnu @mkovaxx I'm getting this type error and I'm not sure what the intended fix is? Am I only supposed to add code under `//TODO`?

```
⚠️  Compiling of exercises/smart_pointers/cow1.rs failed! Please try again. Here's the output:
error[E0308]: mismatched types
  --> exercises/smart_pointers/cow1.rs:74:23
   |
74 |         match abs_all(&mut input) {
   |               ------- ^^^^^^^^^^ expected `&mut Cow<'_, [i32]>`, found `&mut &mut Vec<{integer}>`
   |               |
   |               arguments to this function are incorrect
   |
   = note: expected mutable reference `&mut std::borrow::Cow<'_, [i32]>`
              found mutable reference `&mut &mut Vec<{integer}>`
note: function defined here
  --> exercises/smart_pointers/cow1.rs:19:4
   |
19 | fn abs_all<'a, 'b>(input: &'a mut Cow<'b, [i32]>) -> &'a mut Cow<'b, [i32]> {
   |    ^^^^^^^         -----------------------------

error: aborting due to previous error
```

**Comment by wh5a** [comment] 2023-09-07 08:54
In fact, I think we should **not** add `to_mut`, as the comment is actually referring to the `to_mut` call inside the `abs_all` function. `owned_mutation` isn't identical to `owned_no_mutation` if you look more closely as the input vector.

**Comment by pchilds** [comment] 2023-09-18 04:16
This should have been checked before merging.
#1620 has presented a regression.
@shadows-withal could you please reopen this issue.

**Comment by shadows-withal** [comment] 2023-09-18 08:01
My bad! I'll push a patch release to address this regression.

**Comment by shadows-withal** [comment] 2023-09-18 08:02
Also, I'll keep this issue open, but @wh5a said it correctly: The comment is correct, the `abs_all` function presents a special behaviour when processing a negative number.

**Comment by wh5a** [comment] 2023-09-18 08:07
Isn't this already fixed by someone else?

**Comment by shadows-withal** [comment] 2023-09-18 08:09
In 33a4f4e454031ea7b318c855625553b413b8afcd, yeah. I'm just keeping the issue open in case anyone else runs into confusion.

**Comment by PranavJayachand** [comment] 2023-09-20 01:04
> In [33a4f4e](https://github.com/rust-lang/rustlings/commit/33a4f4e454031ea7b318c855625553b413b8afcd), yeah. I'm just keeping the issue open in case anyone else runs into confusion.

And thank you for that -- was really confused on what to change at this point working through the exercises! Good to read through the thread and figure it out.

**Comment by mo8it** [comment] 2024-07-07 15:03
Further improved in https://github.com/rust-lang/rustlings/commit/9d7b973a62d3c0181be386752d72fa0722fe6135

**Closed by mo8it** 2024-07-07 15:03 UTC
