### ISSUE TITLE
Pretty much exact same exercise: Conversions - from_into and from_str

### ISSUE THREAD

**Issue by NicolasResier** [rust-lang/rustlings#549] opened 2020-10-04 21:19 UTC
Dear,

Thank you very much for all these wonderful exercises. They were loads of fun and very interesting.
I would like to report however that there are 2 exercises at the end that are pretty much the same:
- Conversions > from_into.rs
- Conversions > from_str.rs

The only difference is that in case of a problem, in one you send a default while in the other you send an error.

Hope this helps.
Greetings,
Nicolas

**Comment by mariusfrinken** [comment] 2020-10-23 11:36
To add to that comment:

Why does the first test for an empty input string expects an error, while all other tests with bad input simply expect the function to panic?

If you want to teach people that returning a well formulated **Error** is the way to go in such circumstances and not just hacking something together with `panic!(),` please make that unambiguously clear.

**Comment by AbdouSeck** [comment] 2020-10-23 11:53
Hi @NicolasResier, thanks for raising this concern. I wrote those two exercises with the goal of highlighting the similarities between the `FromStr` and `From` traits. While these have somewhat different API's when used, their implementation are very similar. Again, the goal here is to make it obvious that `From` and `FromStr` look _**very very**_ similar.

@mariusfrinken, I am not sure what you're getting at. But the reason behind having `#[should_panic]` test cases is to handle situations where a user `unwraps` without actually checking that the returned value is `ok`. Also, in `from_str.rs`, your goal is not to write unit tests; the tests are there to check that you've implemented the code above it properly.

With that said, if you have any suggestions for what the exercises should be, please share them either via this issue or via a pull request. I am more than happy to discuss this further. And, sorry about the delayed response.

Thanks,
Abdou

**Comment by mariusfrinken** [comment] 2020-10-23 12:18
@AbdouSeck 
To clarify:
The naive approach I took to this exercise:
0. copy everything from the other similar exercise, make some slight changes
1. Oh I should throw an error, but what kind of error?
2. Let's look into the test cases to see the expected behaviour
3. Oh you expect that thing to panic
4. Let's try calling `panic!()` instead of messing with the Error notation 
(honestly my personal problem here was, that I just looked at Chapter 9. Error Handling, and there I found no detailed explanation on how to create your own Errors etc)
5. It worked for all test cases except the first one
6. Confusion
7. ...
8. I realize that it is indeed bad practice to use `panic!()` here, but I feel like the other testcases should reflect that, too.

My recommendation:
Define ( Or Make the user define) multiple Error types for the different input issues the function may have AND test it properly, such that the tests passes only if the correct error is returned. From my point of view, this exercise should teach you that casting is a task where one has to be aware of the responsibility of returning either a correctly formed result or a **useful** error. In the current version, the last aspect is missing IMHO.

**Comment by AbdouSeck** [comment] 2020-10-23 12:30
Hi @mariusfrinken, if you look at [this line](https://github.com/rust-lang/rustlings/blob/f38f42f17dd0e12cf3c1f4bcf27029a2e1c2a439/exercises/conversions/from_str.rs#L24), you'll see that `type Err = String;` means that the `Result` variants returned by the implementation should be of type `String`. So, the returned value should be `Ok<Person>` or `Err<String>`.

Defining error types adds quite a bit of confusion to the exercise since the main goal is to highlight and the `FromStr` and its possible implementations.

You are definitely right about handling errors specifically, but I believe that we have exercises that come way before these conversion exercises that already try to do that.
But if you have the bandwidth, please feel free to add error types to be returned and assign it accordingly.

Thanks,
Abdou

**Comment by mariusfrinken** [comment] 2020-10-23 13:59
@AbdouSeck Ok, thanks for your answers. As you alluded to it, actually `errors1` and `result1` should cover that, but somehow the lessons from that exercises did not really persist on my mind. 
No I know more and I also see your point.
Unfortunately, I don't have the bandwidth right now, but I am still a fan of making the testcases consistent: why not use `assert!("BadString".parse::<Person>().is_err());`
for all of them?

**Comment by AbdouSeck** [comment] 2020-10-23 14:03
@mariusfrinken `assert!("BadString".parse::<Person>().is_err());` should work fine, as well. If that's within your reach, please feel free to make the changes. Otherwise, I'll try and make those updates over the weekend or next week.

Thanks,
Abdou

**Closed** 2020-12-12 13:18 UTC
