### ISSUE TITLE
Some compiler errors are not highlighted in editor (vscode)

### ISSUE THREAD

**Issue by Lexey40o** [rust-lang/rustlings#1628] opened 2023-08-18 19:14 UTC
`rustc --version`: rustc 1.71.1 (eb26296b5 2023-08-03)
`rustlings --version`: v5.5.1
OS: Microsoft Windows 10 Home 10.0.19045 Build 19045
`rust-analyzer` vscode plugin version: v0.4.1627
vscode version: 1.81.1
<details><summary>ls -la</summary>
<p>

```
total 29597
drwxrwxrwx 1 user user     512 Aug 17 22:16 .
drwxrwxrwx 1 user user     512 Jul 28 12:07 ..
-rwxrwxrwx 1 user user   59202 May 17 13:09 .all-contributorsrc
drwxrwxrwx 1 user user     512 May  2 12:35 .devcontainer
-rwxrwxrwx 1 user user     109 May  2 12:35 .editorconfig
drwxrwxrwx 1 user user     512 Aug 17 16:54 .git
drwxrwxrwx 1 user user     512 May  2 12:35 .github
-rwxrwxrwx 1 user user     224 May 17 13:09 .gitignore
-rwxrwxrwx 1 user user     169 May  2 12:35 .gitpod.yml
-rwxrwxrwx 1 user user      61 May 17 13:09 .markdownlint.yml
drwxrwxrwx 1 user user     512 May  2 12:35 .vscode
-rwxrwxrwx 1 user user   76274 May 17 13:09 AUTHORS.md
-rwxrwxrwx 1 user user   47175 May 17 13:09 CHANGELOG.md
-rwxrwxrwx 1 user user    4301 May  2 12:35 CONTRIBUTING.md
-rwxrwxrwx 1 user user   19047 May 17 13:09 Cargo.lock
-rwxrwxrwx 1 user user     616 May 17 13:09 Cargo.toml
-rwxrwxrwx 1 user user    1117 May  2 12:35 LICENSE
-rwxrwxrwx 1 user user    6720 May 17 13:09 README.md
drwxrwxrwx 1 user user     512 May  2 12:35 exercises
-rwxrwxrwx 1 user user    1572 May  2 12:35 flake.lock
-rwxrwxrwx 1 user user    2032 May 17 13:09 flake.nix
-rwxrwxrwx 1 user user   43455 May 17 13:09 info.toml
-rwxrwxrwx 1 user user    3116 May  2 12:35 install.ps1
-rwxrwxrwx 1 user user    4846 May  2 12:35 install.sh
-rwxrwxrwx 1 user user     212 May 17 13:09 oranda.json
-rwxrwxrwx 1 user user    9082 Aug 17 22:38 rust-project.json
-rwxrwxrwx 1 user user     284 May  2 12:35 shell.nix
drwxrwxrwx 1 user user     512 May 17 13:09 src
drwxrwxrwx 1 user user     512 Aug 17 22:17 target
-rwxrwxrwx 1 user user 1437696 May  2 12:59 temp_13664_ThreadId1.pdb
-rwxrwxrwx 1 user user 2715648 Jul 17 21:33 temp_14188_ThreadId1.pdb
-rwxrwxrwx 1 user user 2715648 Aug 17 21:39 temp_14824_ThreadId1.pdb
-rwxrwxrwx 1 user user 2715648 May 17 12:58 temp_16652_ThreadId1.pdb
-rwxrwxrwx 1 user user 2715648 Jul 17 21:22 temp_18980_ThreadId1.pdb
-rwxrwxrwx 1 user user 2699264 May  2 15:10 temp_19512_ThreadId1.pdb
-rwxrwxrwx 1 user user 2715648 Aug 17 21:53 temp_20004_ThreadId1.pdb
-rwxrwxrwx 1 user user 1437696 May  2 13:56 temp_20164_ThreadId1.pdb
-rwxrwxrwx 1 user user 2715648 Aug 17 16:48 temp_21876_ThreadId1.pdb
-rwxrwxrwx 1 user user 2715648 Jul 15 15:54 temp_24296_ThreadId1.pdb
-rwxrwxrwx 1 user user 2699264 May  3 19:07 temp_26588_ThreadId1.pdb
-rwxrwxrwx 1 user user 2715648 May 17 13:18 temp_3312_ThreadId1.pdb
drwxrwxrwx 1 user user     512 May  2 12:35 tests
```

</p>
</details>

When going through exercise [enums3.rs](https://github.com/rust-lang/rustlings/blob/5.5.1/exercises/enums/enums3.rs), I noticed that certain errors won't be highlighted in the editor (vscode), but will be caught by `rustlings run enums3`. Here's [a modified version of enums3.rs that contains errors which should be highlighted but are not](https://gist.github.com/Lexey40o/f201bc900c6abfc9ce7fe79325f90e7c#file-enums3-rs-L43-L44).
An interesting bit is that if you delete `not_an_inscope_variable`, I _do_ get error highlighting for the wrong number of arguments error ([E0107](https://doc.rust-lang.org/stable/error_codes/E0107.html)).

I'm guessing this has to do with the relationship between the unique project structure of rustlings and the `rust-analyzer` plugin. I was not able to reproduce this problem inside [a project with a normal structure](https://gist.github.com/Lexey40o/9c27a5e5c0397d7d5cd77bf59fc0cb8b), as the errors were appropriately highlighted inside the editor.

If this turns out to be a `rust-analyzer` problem, I'd be happy to open an issue there.

**Comment by mo8it** [comment] 2024-06-19 11:29
In the upcoming version 6, we use `Cargo.toml` instead of `project.json`, but this issue still exists. So it is a `rust-analyzer` issue.

**Comment by JaKXz** [comment] 2024-06-19 21:24
If the project structure is going to be changed in future that sounds like a good solution, but, I think I'm seeing a similar problem where I can't use `rust-analyzer` in vscode because it thinks all the files in `exercises/` are not part of the crate hierarchy and I just get the https://rust-analyzer.github.io/manual.html#unlinked-file message :( 

Is there anything obvious I might be doing wrong?

**Comment by mo8it** [comment] 2024-06-19 23:04
@JaKXz Did you run `rustlings lsp`?

**Comment by JaKXz** [comment] 2024-06-20 04:45
That definitely helped, thank you! Now I think I am seeing what OP mentioned:

<img width="1868" alt="image" src="https://github.com/rust-lang/rustlings/assets/2642545/e8c5c023-fcd2-454f-b7e3-ad3e58ea88b2">

**Comment by mo8it** [comment] 2024-06-20 08:58
@JaKXz Don't worry, it is easy to miss! This is why this step will not be needed in version 6 :)

**Comment by mo8it** [comment] 2024-07-07 14:34
@Veykril What is the best next step? Should I open an issue in the `rust-analyzer` repo or is there already one that I couldn't find?

This isn't specific to VS-Code. I can also reproduce it in Helix. Here is how to reproduce it in VS-Code:

```bash
cargo install rustlings
rustlings init
cd rustlings
code .
```

Almost all files should contain errors, but some errors aren't shown.

**Comment by Veykril** [comment] 2024-07-07 14:48
Can you be a bit more specific? 😅 What errors are missing where, I need a concrete example

**Comment by Veykril** [comment] 2024-07-07 14:49
Ah you are talking about `cargo check` diagnostics I suppose

**Comment by Veykril** [comment] 2024-07-07 14:54
It seems cargo is not reporting all errors. r-a invokes `cargo check --workspace --message-format=json-diagnostic-rendered-ansi --manifest-path Cargo.toml --all-targets` which seems to exit out early before checking all crates, or the output at least does not contain all errors here. So this is a cargo bug.

**Comment by mo8it** [comment] 2024-07-07 14:54
![image](https://github.com/rust-lang/rustlings/assets/76752051/60d47c89-f20c-4f24-906c-80b6e3d216a3)

Yes, `cargo check` errors and warnings are only shown in some of the exercises, not all.

This is how it is supposed to look like:

![image](https://github.com/rust-lang/rustlings/assets/76752051/e3f58691-edbd-4e52-ba05-8ae06e05d5aa)

I got the second screenshot after saving the file for 2-3 times.
It seems like Rust-Analyzer stops at some point and which files show errors and warning is controlled by some race condition.

**Comment by mo8it** [comment] 2024-07-07 14:56
> It seems cargo is not reporting all errors. r-a invokes `cargo check --workspace --message-format=json-diagnostic-rendered-ansi --manifest-path Cargo.toml --all-targets` which seems to exit out early before checking all crates, or the output at least does not contain all errors here. So this is a cargo bug.

Alright, I will report it to Cargo then. Thanks :D

**Comment by mo8it** [comment] 2024-07-07 15:35
@Veykril The required Cargo option is `--keep-going`. Adding `check.extraArgs = ["--keep-going"]` fixed this issue. But this would be something that everyone has to configure in the editor.

Is it fine to add `--keep-going` to the check command [here](https://github.com/rust-lang/rust-analyzer/blob/a5b21ea0aa644dffd7cf958b43f11f221d53404e/crates/flycheck/src/lib.rs#L484)? I can open a PR.

This should be done depending on the available Rust version like [this snippet](https://github.com/rust-lang/rust-analyzer/blob/a5b21ea0aa644dffd7cf958b43f11f221d53404e/crates/project-model/src/build_scripts.rs#L125-L127) because [`--keep-going` was stabilized in 1.74](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-174-2023-11-16).

**Comment by Veykril** [comment] 2024-07-07 15:53
Oh that is a good point. Yes we should unconditionally throw that into the `FlycheckConfig::CargoCommand` branch

**Comment by mo8it** [comment] 2024-07-08 09:27
A fix has been merged into Rust-Analyzer :D

**Closed by mo8it** 2024-07-08 09:27 UTC
