### ISSUE TITLE
Rustlings finds "new" compile errors when coming back to course.

### ISSUE THREAD

**Issue by dcechano** [rust-lang/rustlings#1321] opened 2023-01-04 18:52 UTC
This error is very simple but very confusing. When navigating the course I will run `rustlings watch` while I work on solutions. I will make changes, check the terminal running `rustlings watch`, read the compile errors and fix until it compiles and I get told to remove `TODO I AM NOT DONE` to move on to next exercise. In this way every exercise is "done" when I move on to the next.
However when I revisit the course and rerun `rustlings watch` to see where I left off I almost invariable am prompted with compile errors on solutions that were literally just compiling the day prior. I thought it was an issue with my changes being saved so I started pushing to my remote fork before I got off, then updating local repo before resuming. That did nothing. 

To confirm this is a bug and not some other issue, I ran `rustlings watch` got the "new" compile error, it told me to go fix something in the `move_semantics` exercise that just compiled fine yesterday. Fix it. See that it brings me back to where I left last night. Close terminal and reopen. Rerun `rustlings watch`: "new" error: something in `vec.rs` exercise. These exercises were finished. I was told my solution compiled and to move on then when I come back they don't compile anymore.

So far this has been my experience with rustlings every time I revisit the course. Not a huge deal but I fully expect that when I fire up `rustlings watch` I will be pointed back to an exercise that was previously compiling. I have no issue with fixing compile errors as its a part of learning the language but I don't understand while they compile at one point then finds, admittedly, very real issues. I shouldn't be told to move on the next exercise. To be clear these compile errors are not erroneous, it is the successful messages that are evidently erroneous. 

I am running Windows 11 and using Powershell to run rustlings watch`.

**Comment by diannasoreil** [comment] 2023-01-05 14:24
Huh yeah, I can't reproduce this. Could you provide a snapshot of your repo that I can clone to check?

**Comment by dcechano** [comment] 2023-01-07 01:47
> Huh yeah, I can't reproduce this. Could you provide a snapshot of your repo that I can clone to check?

Please fork my repo right now as it is producing a compile error for `tests3.rs`. I made it all the way to `iterators2.rs`, recompiled and then it randomly wants me to go back to `tests3.rs` but it was compiling before (hence why I am on `iterators2.rs`.)!! There error is especially confusing to boot. Attached is a snippet of my Powershell window. I appreciate you looking into this!
<img width="449" alt="image" src="https://user-images.githubusercontent.com/43017290/211125757-ffd392cf-4ee0-4710-a870-3e0474a51ded.png">

**Comment by nmay231** [comment] 2023-05-01 04:34
Maybe you are interacting with the wrong remote repo? You don't want to pull from *this* repository and reset your progress.

Check which remote is upstream with `git status -sb`, and `git remote -v`.

**Comment by mo8it** [comment] 2024-03-30 16:55
Closing because of missing response by the author.

**Closed by mo8it** 2024-03-30 16:55 UTC
