### ISSUE TITLE
Show diff between user's submitted code and actual minimal version of solution (say gold solution)

### ISSUE THREAD

**Issue by vivekvpandya** [rust-lang/rustlings#684] opened 2021-03-27 03:57 UTC
Most of the time expectation is that there should be no diff between user's correct submission and gold.
Benefit of this feature is that it give more insights to user in case there is a diff.

For example in given code below, it will give feedback to user that he/she should read more about `mut` :

```
// Correct Solution                                                                                  // Correct solution but extra mut on line 7
  6 fn main() {                                                                                          |  6 fn main() {
  7     let vec0 = Vec::new();                                                                           |  7     let mut vec0 = Vec::new();   // <--- here mut is not required
  8                                                                                                      |  8
  9     let mut vec1 = fill_vec( vec0);                                                                  |  9     let mut vec1 = fill_vec( vec0);
 10                                                                                                      | 10
 11     println!("{} has length {} content `{:?}`", "vec1", vec1.len(), vec1);                           | 11     println!("{} has length {} content `{:?}`", "vec1", vec1.len(), vec1);
 12                                                                                                      | 12
 13     vec1.push(88);                                                                                   | 13     vec1.push(88);
 14                                                                                                      | 14
 15     println!("{} has length {} content `{:?}`", "vec1", vec1.len(), vec1);                           | 15     println!("{} has length {} content `{:?}`", "vec1", vec1.len(), vec1);
 16 }                                                                                                    | 16 }
 17                                                                                                      | 17
 18 fn fill_vec(mut vec: Vec<i32>) -> Vec<i32> {                                                         | 18 fn fill_vec(mut vec: Vec<i32>) -> Vec<i32> {
 19     vec.push(22);                                                                                    | 19     vec.push(22);
 20     vec.push(44);                                                                                    | 20     vec.push(44);
 21     vec.push(66);                                                                                    | 21     vec.push(66);
 22                                                                                                      | 22
 23     vec                                                                                              | 23     vec
 24 }                                                                                                    | 24 }
```

**Comment by rytheo** [comment] 2022-02-07 04:33
Related to #293

**Comment by mo8it** [comment] 2024-03-27 20:51
Closing because it is kind of duplicate of https://github.com/rust-lang/rustlings/issues/293

The unique thing here is the diff idea. But I don't think that it is helpful with bigger exercises. I would rather prefer putting the solution on the disk of the user and they can open it next to the exercise :)

**Closed by mo8it** 2024-03-27 20:51 UTC
