### ISSUE TITLE
Windows powershell installation issues

### ISSUE THREAD

**Issue by BroadbentJim** [rust-lang/rustlings#1759] opened 2023-11-06 21:24 UTC
Following the instructions as written to install on Windows, I have the error:

```
PS C:\Windows\system32> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
PS C:\Windows\system32> Start-BitsTransfer -Source https://ps1.rustlings.cool -Destination $env:TMP/install_rustlings.ps1; Unblock-File $env:TMP/install_rustlings.ps1; Invoke-Expression $env:TMP/install_rustlings.ps1                        Start-BitsTransfer : The resource loader cache doesn't have loaded MUI entry. (Exception from HRESULT: 0x80073B01)      At line:1 char:1                                                                                                        + Start-BitsTransfer -Source https://ps1.rustlings.cool -Destination $e ...                                             + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], COMException                                          + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.BackgroundIntelligentTransfer.Mana     gement.NewBitsTransferCommand

Unblock-File : Cannot find path 'C:\Users\jim\AppData\Local\Temp\install_rustlings.ps1' because it does not exist.
At line:1 char:100
+ ... ll_rustlings.ps1; Unblock-File $env:TMP/install_rustlings.ps1; Invoke ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\jim\Ap...l_rustlings.ps1:String) [Unblock-File], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : FileNotFound,Microsoft.PowerShell.Commands.UnblockFileCommand

C:\Users\jim\AppData\Local\Temp/install_rustlings.ps1 : The term
'C:\Users\jim\AppData\Local\Temp/install_rustlings.ps1' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ C:\Users\jim\AppData\Local\Temp/install_rustlings.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\jim\Ap...l_rustlings.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32>
```

Unsure what to do. I've got wsl but have installed Rust on Windows so would like to use this package on Windows.

**Comment by jbouganim-parallel** [comment] 2023-11-13 23:25
experiencing the same thing.  it seems the issue is that `https://ps1.rustlings.cool` is down

**Comment by jbouganim-parallel** [comment] 2023-11-13 23:42
found an alternate command here:

```
Start-BitsTransfer -Source https://raw.githubusercontent.com/rust-lang/rustlings/main/install.ps1 -Destination $env:TMP/install_rustlings.ps1; Unblock-File $env:TMP/install_rustlings.ps1; Invoke-Expression $env:TMP/install_rustlings.ps1
```

**Comment by BroadbentJim** [comment] 2023-11-13 23:43
I managed to install it via downloading the whole repo and then doing cargo install rustlings from the rustlings folder. Then when you have your cmdline in the rustlings folder and run rustlings watch, it works okay. Let me know if this solution works or not and I can try and think more about what I did.

**Comment by mo8it** [comment] 2024-03-28 01:06
Should be fixed now thanks to @jbouganim-parallel

**Closed** 2024-03-28 01:06 UTC
