### ISSUE TITLE
clippy1 no longer fails linting

### ISSUE THREAD

**Issue by radicale** [rust-lang/rustlings#906] opened 2022-01-06 20:24 UTC
The relative `float_cmp` lint has been demoted from the _correctness_ category (default **deny**) to _pedantic_ (default **allow**) in the following PR:

https://github.com/rust-lang/rust-clippy/pull/7692

Consequently, the _clippy1_ exercise doesn't fail linting and leaves the user with nothing to fix.  Possible solutions include rewriting the exercise to leverage another lint or adding the `-D clippy::float_cmp` arguments when invoking `clippy`.

**Comment by radicale** [comment] 2022-01-06 20:54
Or perhaps it would be more appropriate to setup the lints in the source files themselves with something like:
`#![deny(clippy::all, clippy::float_cmp)]`

**Comment by qq8244353** [comment] 2022-04-04 03:14
I was working on the exercise and this problem confused me a lot, so I think it needs to be fixed.
I confirmed attaching the attribute mentioned above to the main function will work, tho I think adding some message in the source code that kindly explains the situation something goes like "This is required because the linter no longer fails due to the recent update" is better. 
If you don’t mind, please let me make a pull request with this content.

**Comment by hilary** [comment] 2022-04-11 23:34
I came to look at the issues today due to clippy not failing. FWIW, of the options discussed, I like adding 

```rust
#![deny(clippy::float_cmp)]
```

best as a quick fix, as it expands on the lesson.

**Comment by diannasoreil** [comment] 2022-04-14 08:40
This is a duplicate of #888, which has been closed by #890, which will make it into the next version.

**Closed by diannasoreil** 2022-04-14 08:40 UTC
