### ISSUE TITLE
Is the Solution to Quiz 2 correct?

### ISSUE THREAD

**Issue by sibkru** [rust-lang/rustlings#2045] opened 2024-07-12 08:17 UTC
I'm new to Rust, so I might be doing something wrong.

In Quiz 2, I was struggling with the following error:

 pub fn transformer(input: Vec<(String, Command)>) -> Vec<String> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type

The solution seems to be to make the Command Enum public.
`
pub enum Command {
    Uppercase,
    Trim,
    Append(usize),
}
`
I wasn't sure if that was a hack or the correct way, so I looked into the solution, which does not declare the enum as public.
But when I copy and paste the solution and look at the rustlings output, I get the same error message I got with my own code (now also for transformer_iter).

rustlings version: 6.0.1
rustc version: 1.79
cargo version: 1.79

Is the solution incorrect, or am I doing something wrong on my side (probably the latter)?

**Comment by mo8it** [comment] 2024-07-12 14:27
You are probably doing something wrong because the solutions are checked in the CI to all compile and run correctly.

Can you please paste your whole exercise code?

**Comment by sibkru** [comment] 2024-07-17 11:12
`// This is a quiz for thefollowing sections:
// - Strings
// - Vecs
// - Move semantics
// - Modules
// - Enums
//
// Let's build a little machine in the form of a function. As input, we're going
// to give a list of strings and commands. These commands determine what action
// is going to be applied to the string. It can either be:
// - Uppercase the string
// - Trim the string
// - Append "bar" to the string a specified amount of times
//
// The exact form of this will be:
// - The input is going to be a Vector of 2-length tuples,
//   the first element is the string, the second one is the command.
// - The output element is going to be a vector of strings.

enum Command {
    Uppercase,
    Trim,
    Append(usize),
}

mod my_module {
    use super::Command;

    // TODO: Complete the function.
    // pub fn transformer(input: ???) -> ??? { ??? }
    pub fn transformer(input: Vec<(String, Command)>) -> Vec<String> {
        let mut result = vec![];
        for line in input.into_iter() {
            match line {
                (a, Command::Uppercase) => {
                    result.push(a.to_uppercase());
                }
                (a, Command::Trim) => {
                    result.push(a.trim().to_string());
                }
                (a, Command::Append(num)) => {
                    result.push(a + &"bar".repeat(num));
                }
            };
        }
        result
    }
}

fn main() {
    // You can optionally experiment here.
}

#[cfg(test)]
mod tests {
    // TODO: What do we need to import to have `transformer` in scope?
    // use ???;
    use super::my_module::transformer;
    use super::Command;

    #[test]
    fn it_works() {
        let input = vec![
            ("hello".to_string(), Command::Uppercase),
            (" all roads lead to rome! ".to_string(), Command::Trim),
            ("foo".to_string(), Command::Append(1)),
            ("bar".to_string(), Command::Append(5)),
        ];
        let output = transformer(input);

        assert_eq!(
            output,
            [
                "HELLO",
                "all roads lead to rome!",
                "foobar",
                "barbarbarbarbarbar",
            ]
        );
    }
}
`

This is my complete exercise code that yields the above-described error.
When I copy the transformer function from here: https://github.com/rust-lang/rustlings/blob/main/solutions/quizzes/quiz2.rs
I get the same error.

**Comment by mo8it** [comment] 2024-07-17 12:21
I can't reproduce it. Very weird.

I also pasted it into the Rust playground and it ran without any problem: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=50188eeb2b80684521e1c7c73282c239

Are you sure `cargo --version` returns the version `1.79`?

Can you please run `rustup update` and try again?

Can you please also share a screenshot of the error in Rustlings?

**Comment by mo8it** [comment] 2024-07-17 13:03
I just ran the checks in the CI on Apple. All solutions ran without a problem:
https://github.com/rust-lang/rustlings/actions/runs/9974536710/job/27562222308?pr=2052

Can you please create a new project with `cargo new quiz2` in some directory, paste your code in https://github.com/rust-lang/rustlings/issues/2045#issuecomment-2233051699 and run it with `cargo clippy` and `cargo test`? Please also do the same with the [solution file](https://github.com/rust-lang/rustlings/blob/183ed3f88f416816312595fde2573b587fd8d999/solutions/quizzes/quiz2.rs). This allows us to separate the problem from Rustlings.

**Comment by sibkru** [comment] 2024-07-17 13:17
Here are the results:
on my exercise:
cargo clippy produces the same error.
cargo test runs fine.
<img width="834" alt="image" src="https://github.com/user-attachments/assets/e810c53f-8539-4250-9840-429ffd548934">
<img width="821" alt="image" src="https://github.com/user-attachments/assets/dbb69ac5-1960-4ab9-8ca1-b12941681fb9">

on solution file:
cargo clippy produces the error.
cargo test runs fine.

<img width="826" alt="image" src="https://github.com/user-attachments/assets/f5d9fc5b-a243-4a3b-a74f-31767170b012">
<img width="822" alt="image" src="https://github.com/user-attachments/assets/8c6cd04c-ce0a-4734-a79d-4d9b0df3bba7">

**Comment by mo8it** [comment] 2024-07-17 14:04
I asked for help on the Rust forum: https://users.rust-lang.org/t/error-only-on-a-specific-target/114552

**Comment by sibkru** [comment] 2024-07-17 14:18
Thanks, I appreciate you taking the time!

**Comment by wezm** [comment] 2024-07-17 22:12
> cargo clippy produces the error.
> cargo test runs fine.

@sibkru since it is clippy that is failing it might be worth including the output of:

    which cargo-clippy

and

    cargo clippy --version

as well.

**Comment by mo8it** [comment] 2024-07-17 22:16
Oh, good idea! It is also worth trying out `cargo check`.

**Comment by mo8it** [comment] 2024-07-30 10:07
@sibkru Did you find time to try the commands above? :)

**Closed** 2024-08-16 09:12 UTC
