### ISSUE TITLE
Tracking progress of solved/unsolved

### ISSUE THREAD

**Issue by torymur** [rust-lang/rustlings#449] opened 2020-06-22 13:31 UTC
Is there a way to see a progress?

It would be nice to see where you are and how many exercises there are left to do.

**Comment by estebanborai** [comment] 2020-07-18 00:27
Hey @torymur!

I think this is a good to have feature! And as I can see in the `main.rs` file, we already have the resources we need to accomplish this!

**Comment by rytheo** [comment] 2020-07-26 23:55
This looks like a duplicate of #360

**Comment by estebanborai** [comment] 2020-07-27 01:41
@rytheo it looks like!

**Comment by jrvidal** [comment] 2020-07-27 06:48
Closing as duplicate then :+1:

**Closed by jrvidal** 2020-07-27 06:48 UTC
Labels: A-source, C-feature-request
