### ISSUE TITLE
threads3.rs solution doesn't compile using rustc rustc 1.82.0 (f6e511eec 2024-10-15)

### ISSUE THREAD

**Issue by kuroega** [rust-lang/rustlings#2152] opened 2024-11-10 09:48 UTC
Rustc: rustc 1.82.0 (f6e511eec 2024-10-15)
Platform: Windows 11 Home 23H2 22631.4391

The test case compiles after made the following changes.

```diff
 fn send_tx(q: Queue, tx: mpsc::Sender<u32>) {
     // TODO: We want to send `tx` to both threads. But currently, it is moved
     // into the first thread. How could you solve this problem?
+    let Queue { first_half, second_half } = q;
     let tx_clone = tx.clone();
     thread::spawn(move || {
-        for val in q.first_half {
+        for val in first_half {
             println!("Sending {val:?}");
            tx_clone.send(val).unwrap();
             thread::sleep(Duration::from_millis(250));
         }
     });

     thread::spawn(move || {
-        for val in q.second_half {
+        for val in second_half {
             println!("Sending {val:?}");
             tx.send(val).unwrap();
             thread::sleep(Duration::from_millis(250));
...
```

**Comment by mo8it** [comment] 2024-11-11 12:49
I can't reproduce this. I tried stable and beta.
All solutions are checked in the CI. Please post the concrete error message if you are sure that the provided solution doesn't compile.

**Closed by mo8it** 2024-11-11 12:49 UTC
