### ISSUE TITLE
invalid array access example is no longer accurate

### ISSUE THREAD

**Issue by dhiltonp** [rust-lang/rustlings#505] opened 2020-08-25 23:22 UTC
https://doc.rust-lang.org/book/ch03-02-data-types.html#invalid-array-element-access

The code sample: 

```
fn main() {
    let a = [1, 2, 3, 4, 5];
    let index = 10;

    let element = a[index];

    println!("The value of element is: {}", element);
}
```

Does not compile with `cargo run` (`cargo 1.45.1 (f242df6ed 2020-07-22)`).

This is good, but means the example is out of date.

**Comment by Amjad50** [comment] 2020-09-02 03:29
I think this should be opened in [rust-lang/book](https://github.com/rust-lang/book) and not here

**Comment by Amjad50** [comment] 2020-09-02 03:53
This is a duplicate of rust-lang/book#2417, should be closed

**Closed** 2020-09-02 08:09 UTC
